/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TempRouteImport } from './routes/temp'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateProjectRouteImport } from './routes/create-project'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProjectsProject_idDashboardRouteImport } from './routes/projects/$project_id/dashboard'

const TempRoute = TempRouteImport.update({
  id: '/temp',
  path: '/temp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateProjectRoute = CreateProjectRouteImport.update({
  id: '/create-project',
  path: '/create-project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProject_idDashboardRoute =
  ProjectsProject_idDashboardRouteImport.update({
    id: '/projects/$project_id/dashboard',
    path: '/projects/$project_id/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-project': typeof CreateProjectRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/temp': typeof TempRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$project_id/dashboard': typeof ProjectsProject_idDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-project': typeof CreateProjectRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/temp': typeof TempRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$project_id/dashboard': typeof ProjectsProject_idDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-project': typeof CreateProjectRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/temp': typeof TempRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$project_id/dashboard': typeof ProjectsProject_idDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-project'
    | '/dashboard'
    | '/login'
    | '/profile-setup'
    | '/temp'
    | '/auth/callback'
    | '/projects'
    | '/projects/$project_id/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-project'
    | '/dashboard'
    | '/login'
    | '/profile-setup'
    | '/temp'
    | '/auth/callback'
    | '/projects'
    | '/projects/$project_id/dashboard'
  id:
    | '__root__'
    | '/'
    | '/create-project'
    | '/dashboard'
    | '/login'
    | '/profile-setup'
    | '/temp'
    | '/auth/callback'
    | '/projects/'
    | '/projects/$project_id/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateProjectRoute: typeof CreateProjectRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  TempRoute: typeof TempRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProject_idDashboardRoute: typeof ProjectsProject_idDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temp': {
      id: '/temp'
      path: '/temp'
      fullPath: '/temp'
      preLoaderRoute: typeof TempRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-project': {
      id: '/create-project'
      path: '/create-project'
      fullPath: '/create-project'
      preLoaderRoute: typeof CreateProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project_id/dashboard': {
      id: '/projects/$project_id/dashboard'
      path: '/projects/$project_id/dashboard'
      fullPath: '/projects/$project_id/dashboard'
      preLoaderRoute: typeof ProjectsProject_idDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateProjectRoute: CreateProjectRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  TempRoute: TempRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProject_idDashboardRoute: ProjectsProject_idDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
